/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts,css}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'Helvetica', 'Arial', 'sans-serif'],
        display: ['Montserrat', 'Helvetica', 'Arial', 'sans-serif'],
      },
    },
  },
  safelist: [
    'bg-[#ECF0F1]',
    'bg-[#BDC3C7]',
    'text-[#2C3E50]',
    'text-[#34495E]',
    'text-[#1A2530]',
    'border-[#E67E22]',
    'bg-[#E67E22]',
    'hover:bg-[#D35400]',
    'text-[#F39C12]',
    'font-sans',
    'font-display',
    'font-bold',
    'text-white',
    'text-4xl',
    'md:text-5xl',
    'text-3xl',
    'md:text-4xl',
    'max-w-7xl',
    'mx-auto',
    'px-4',
    'py-16',
    'sm:px-6',
    'lg:px-8',
    'grid',
    'grid-cols-1',
    'sm:grid-cols-2',
    'gap-6',
    'rounded-lg',
    'shadow-lg',
    'overflow-hidden',
    'transition-transform',
    'duration-300',
    'hover:scale-105',
    'flex',
    'flex-col',
    'items-center'
  ],
  plugins: [],
}
